In [ ]:
# Encoding stuff
docs = ["Alex is a CEO","our CEO is here","Best is best","CEO is a best"]
v = {} #vocabulary
cp = 0 # counting variable
for d in docs:
  for w in d.split():
    if w not in v:
      cp = cp+1
      v[w] = cp
print(v)

{'Alex': 1, 'is': 2, 'a': 3, 'CEO': 4, 'our': 5, 'here': 6, 'Best': 7, 'best': 8}


In [ ]:
def one_hot_vect_technique(input):
  encoding = []
  for w in input.split():
    x = [0]*len(v)
    if w in v:
      x[v[w]-1] = 1
    encoding.append(x)
  return encoding

In [ ]:
print(docs[1])
one_hot_vect_technique(docs[1])

our CEO is here


[[0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0]]

In [ ]:
one_hot_vect_technique("CEO here")

[[0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0]]

In [ ]:


S1 = 'dog bites man'
S2 ='man bites dog'
S3 = 'dog eats meat'
S4 = 'man eats food'
"""
S1 = 'dog bites man'
S2 = 'man bites dog'
S3 = 'dog eats meat'
S4 = 'man eats food'
"""

"\nS1 = 'dog bites man'\nS2 = 'man bites dog'\nS3 = 'dog eats meat'\nS4 = 'man eats food'\n"

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

#data = [docs[0].split(),docs[1].split(),docs[2].split(),docs[3].split()]
data = [S1.split(), S2.split(), S3.split(), S4.split()]
v = data[0] + data[1] + data[2] + data[3]
print("data", data)
le = LabelEncoder()
iencoded = le.fit_transform(v) # integer encoder
print("Label Encoding",iencoded)

print("---Trying with one hot encoder comparison stuff ----")
ohencoder = OneHotEncoder()
ohencoded = ohencoder.fit_transform(data).toarray()
print("----ne hot encoded Matrix display result----\n",ohencoded)

data [['dog', 'bites', 'man'], ['man', 'bites', 'dog'], ['dog', 'eats', 'meat'], ['man', 'eats', 'food']]
Label Encoding [1 0 4 4 0 1 1 2 5 4 2 3]
---Trying with one hot encoder comparison stuff ----
----ne hot encoded Matrix display result----
 [[1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 0.]]


In [ ]:
print(type(docs[0]))

<class 'str'>


In [ ]:
# Little bit of BoW
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(binary=True)

bow_rep = count_vect.fit_transform(docs)

print("Our vocabulary: ", count_vect.vocabulary_)

print("BoW representation for '",docs[0],"': ", bow_rep[0].toarray())
print("BoW representation for ",docs[1],"': ",bow_rep[1].toarray())

temp = count_vect.transform(["CEO is manager"])
print("Bow representation for 'CEO is manager':",
temp.toarray())

Our vocabulary:  {'alex': 0, 'is': 4, 'ceo': 2, 'our': 5, 'here': 3, 'best': 1}
BoW representation for ' Alex is a CEO ':  [[1 0 1 0 1 0]]
BoW representation for  our CEO is here ':  [[0 0 1 1 1 1]]
Bow representation for 'CEO is manager': [[0 0 1 0 1 0]]


In [7]:
# Word embedding
from gensim.models import Word2Vec, KeyedVectors
from gensim.test.utils import common_texts


our_model = Word2Vec(common_texts, window=5, min_count=1, workers=4)
#Save the model
our_model.save("tempmodel.w2v")
#Inspect the model by looking for the most similar words for a test word.
print(our_model.wv.most_similar('computer', topn=5))
#Let us see what the 10-dimensional vector for 'computer' looks like.
#print(our_model['computer']) # error Word2Vec Object is not subscriptable

[('system', 0.21617139875888824), ('survey', 0.04468922317028046), ('interface', 0.015203381888568401), ('time', 0.0019510635174810886), ('trees', -0.03284316882491112)]


In [16]:
!python -m spacy download en_core_web_sm
!pip install numpy
!pip install pandas
!pip install scikit-learn
!pip install matplotlib

2023-08-25 15:48:24.718873: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 25.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [10]:
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load()

doc = nlp("Canada is a large country")

print(doc.vector)

[-2.44864374e-01 -1.56845257e-01 -5.19747622e-02  5.86494267e-01
  8.10811967e-02 -1.65754989e-01  7.57052720e-01  2.63185889e-01
  1.40734492e-02  2.51211464e-01  2.43307427e-01 -2.79111534e-01
 -3.70179832e-01  5.22314429e-01 -5.23915410e-01  4.84695425e-03
  4.30857569e-01 -2.19760254e-01 -3.72532457e-01  1.71566337e-01
 -2.67529279e-01  2.24802848e-02 -3.03287357e-01 -1.04288436e-01
  1.51315406e-01 -5.31261384e-01  4.36048269e-01  2.97305524e-01
  4.72418487e-01  3.90211403e-01  2.69951403e-01  2.36672014e-01
  4.59462464e-01 -4.97865111e-01 -1.82451054e-01 -1.67997599e-01
  1.93978697e-01  5.16766071e-01 -2.88335413e-01  3.74710053e-01
 -1.11499667e-01  3.33659947e-01  5.49611822e-02  2.53970414e-01
 -5.02043903e-01  3.85194987e-01 -1.86397389e-01  8.60191345e-01
  2.11835742e-01 -1.24764726e-01 -7.09948778e-01  7.70933092e-01
 -1.79754198e-01 -6.63751960e-01 -4.01271343e-01  1.83464423e-01
 -2.96254933e-01  7.63848484e-01 -3.35624158e-01 -1.81755573e-01
  5.62856086e-02 -5.20981

In [18]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import _stop_words

In [19]:
try:
  imported_data = pd.read_csv('sample_data/data.csv',encoding = "ISO-8859-1")
except Exception:
  print("COuldn't import the data")

In [21]:
display(imported_data.shape)

(8000, 15)

In [24]:
print(imported_data['relevance'].value_counts())

no          6571
yes         1420
not sure       9
Name: relevance, dtype: int64


In [27]:
print(imported_data.shape)

(8000, 15)


In [28]:
imported_data['relevance'].value_counts()/imported_data.shape[0]

no          0.821375
yes         0.177500
not sure    0.001125
Name: relevance, dtype: float64

In [30]:
# Would like only assured data
imported_data = imported_data[imported_data.relevance != "not sure"]
imported_data.shape

(7991, 15)

In [34]:
imported_data['relevance'] = imported_data.relevance.map({'yes':1,'no':0})
text = imported_data[['text']]
relevance = imported_data[['relevance']]
display(text)
print(":::::::::::::RELEVANCE:::::::::::")
display(relevance)

text
0     NEW YORK -- Yields on most certificates of dep...
1     The Wall Street Journal Online</br></br>The Mo...
2     WASHINGTON -- In an effort to achieve banking ...
3     The statistics on the enormous costs of employ...
4     NEW YORK -- Indecision marked the dollar's ton...
...                                                 ...
7995  Secretary of Commerce Charles W. Sawyer said y...
7996  U.S. stocks inched up last week, overcoming co...
7997  Ben S. Bernanke cleared a key hurdle Thursday ...
7998  The White House's push to contract out many fe...
7999  NEW YORK. April 17-Automobile stocks put on th...

[7991 rows x 1 columns]

:::::::::::::RELEVANCE:::::::::::


relevance
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
...         ...
7995        NaN
7996        NaN
7997        NaN
7998        NaN
7999        NaN

[7991 rows x 1 columns]

In [35]:
# Stop words removal
import string
stopwords = _stop_words.ENGLISH_STOP_WORDS
def process(d):
  d = "".join([char for char in d if char not in string.punctuation and not char.isdigit()])
  d = "".join([char for char in d if string not in stopwords])
  return d

In [49]:
import sklearn
from sklearn.model_selection import train_test_split

X = imported_data.text
y = imported_data.relevance
print(X.shape, y.shape)
print("---------Printing y ----")
print(y)
X_train, X_test, y_train,y_test = train_test_split(X,y, random_state=1)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)


(7991,) (7991,)
---------Printing y ----
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
7995   NaN
7996   NaN
7997   NaN
7998   NaN
7999   NaN
Name: relevance, Length: 7991, dtype: float64
(5993,) (5993,)
(1998,) (1998,)


In [39]:
v = CountVectorizer(preprocessor = process)
X_train_dtm = v.fit_transform(X_train)
X_test_dtm = v.transform(X_test)

print(X_train_dtm.shape,X_test_dtm.shape)

(5993, 66351) (1998, 66351)


In [47]:
# Multinomial Naive Bayes Classifier usage
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix

naiveb = MultinomialNB()
print("::::Training feature y ::::")
print(y_train)
#%time naiveb.fit(X_train_dtm, y_train)
print(X_test_dtm)
#y_pred_class = naiveb.predict(X_test_dtm)

#print("Accuracy: ", metrics.accuracy_score(y_test, y_pred_class))
# print the confusion matrix
#cnf_matrix = confusion_matrix(y_test, y_pred_class)



::::Training feature y ::::
3002   NaN
2002   NaN
486    NaN
5426   NaN
440    NaN
        ..
7944   NaN
5198   NaN
3985   NaN
235    NaN
5163   NaN
Name: relevance, Length: 5993, dtype: float64
  (0, 764)	1
  (0, 1095)	1
  (0, 1299)	1
  (0, 3105)	1
  (0, 5326)	1
  (0, 7960)	1
  (0, 8836)	1
  (0, 9095)	1
  (0, 9207)	1
  (0, 9430)	1
  (0, 9484)	1
  (0, 12679)	1
  (0, 16257)	1
  (0, 16779)	1
  (0, 17438)	1
  (0, 17985)	3
  (0, 18147)	1
  (0, 18648)	1
  (0, 19092)	1
  (0, 19627)	1
  (0, 20489)	1
  (0, 21010)	1
  (0, 21065)	3
  (0, 21176)	1
  (0, 21303)	1
  :	:
  (1997, 54236)	1
  (1997, 54308)	1
  (1997, 56615)	1
  (1997, 57342)	1
  (1997, 57492)	1
  (1997, 57863)	1
  (1997, 57898)	1
  (1997, 58543)	1
  (1997, 59537)	1
  (1997, 59569)	6
  (1997, 59615)	2
  (1997, 59770)	1
  (1997, 60251)	5
  (1997, 61235)	1
  (1997, 61313)	1
  (1997, 61898)	1
  (1997, 62296)	1
  (1997, 63012)	1
  (1997, 63460)	1
  (1997, 63504)	1
  (1997, 63522)	1
  (1997, 63787)	2
  (1997, 63793)	1
  (1997, 64448)	1
  (1

In [ ]:
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plot_confusion_matrix(cnf_matrix, classes=['Not Relevant','Relevant'],normalize=True,
                      title='Confusion matrix with max 5000 features')